server:
  port: 80


spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000
    url: jdbc:mysql://sh-cynosdbmysql-grp-00s9vr3u.sql.tencentcdb.com:25365/springboot_demo
    username: root
    password: Z(fmBY&8
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
