package com.tencent.wxcloudrun.mapper;

import com.tencent.wxcloudrun.model.DataPo;
import com.tencent.wxcloudrun.model.DataPoExample;
import java.util.List;

public interface DataPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    int insert(DataPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    int insertSelective(DataPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    List<DataPo> selectByExample(DataPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    DataPo selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DataPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataPo record);
}