package com.tencent.wxcloudrun.model;

public class DataPoWithBLOBs extends DataPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.round
     *
     * @mbg.generated
     */
    private String round;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.qizhi
     *
     * @mbg.generated
     */
    private String qizhi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.year
     *
     * @mbg.generated
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.turn
     *
     * @mbg.generated
     */
    private String turn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.butieNum
     *
     * @mbg.generated
     */
    private String butienum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.butieStandard
     *
     * @mbg.generated
     */
    private String butiestandard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.shouldAmount
     *
     * @mbg.generated
     */
    private String shouldamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.actualAmount
     *
     * @mbg.generated
     */
    private String actualamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.issueDate
     *
     * @mbg.generated
     */
    private String issuedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.registrationDate
     *
     * @mbg.generated
     */
    private String registrationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.phoneNum
     *
     * @mbg.generated
     */
    private String phonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.code
     *
     * @return the value of data.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.code
     *
     * @param code the value for data.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.name
     *
     * @return the value of data.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.name
     *
     * @param name the value for data.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.address
     *
     * @return the value of data.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.address
     *
     * @param address the value for data.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.type
     *
     * @return the value of data.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.type
     *
     * @param type the value for data.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.round
     *
     * @return the value of data.round
     *
     * @mbg.generated
     */
    public String getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.round
     *
     * @param round the value for data.round
     *
     * @mbg.generated
     */
    public void setRound(String round) {
        this.round = round == null ? null : round.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.qizhi
     *
     * @return the value of data.qizhi
     *
     * @mbg.generated
     */
    public String getQizhi() {
        return qizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.qizhi
     *
     * @param qizhi the value for data.qizhi
     *
     * @mbg.generated
     */
    public void setQizhi(String qizhi) {
        this.qizhi = qizhi == null ? null : qizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.year
     *
     * @return the value of data.year
     *
     * @mbg.generated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.year
     *
     * @param year the value for data.year
     *
     * @mbg.generated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.turn
     *
     * @return the value of data.turn
     *
     * @mbg.generated
     */
    public String getTurn() {
        return turn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.turn
     *
     * @param turn the value for data.turn
     *
     * @mbg.generated
     */
    public void setTurn(String turn) {
        this.turn = turn == null ? null : turn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.butieNum
     *
     * @return the value of data.butieNum
     *
     * @mbg.generated
     */
    public String getButienum() {
        return butienum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.butieNum
     *
     * @param butienum the value for data.butieNum
     *
     * @mbg.generated
     */
    public void setButienum(String butienum) {
        this.butienum = butienum == null ? null : butienum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.butieStandard
     *
     * @return the value of data.butieStandard
     *
     * @mbg.generated
     */
    public String getButiestandard() {
        return butiestandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.butieStandard
     *
     * @param butiestandard the value for data.butieStandard
     *
     * @mbg.generated
     */
    public void setButiestandard(String butiestandard) {
        this.butiestandard = butiestandard == null ? null : butiestandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.shouldAmount
     *
     * @return the value of data.shouldAmount
     *
     * @mbg.generated
     */
    public String getShouldamount() {
        return shouldamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.shouldAmount
     *
     * @param shouldamount the value for data.shouldAmount
     *
     * @mbg.generated
     */
    public void setShouldamount(String shouldamount) {
        this.shouldamount = shouldamount == null ? null : shouldamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.actualAmount
     *
     * @return the value of data.actualAmount
     *
     * @mbg.generated
     */
    public String getActualamount() {
        return actualamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.actualAmount
     *
     * @param actualamount the value for data.actualAmount
     *
     * @mbg.generated
     */
    public void setActualamount(String actualamount) {
        this.actualamount = actualamount == null ? null : actualamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.account
     *
     * @return the value of data.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.account
     *
     * @param account the value for data.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.issueDate
     *
     * @return the value of data.issueDate
     *
     * @mbg.generated
     */
    public String getIssuedate() {
        return issuedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.issueDate
     *
     * @param issuedate the value for data.issueDate
     *
     * @mbg.generated
     */
    public void setIssuedate(String issuedate) {
        this.issuedate = issuedate == null ? null : issuedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.registrationDate
     *
     * @return the value of data.registrationDate
     *
     * @mbg.generated
     */
    public String getRegistrationdate() {
        return registrationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.registrationDate
     *
     * @param registrationdate the value for data.registrationDate
     *
     * @mbg.generated
     */
    public void setRegistrationdate(String registrationdate) {
        this.registrationdate = registrationdate == null ? null : registrationdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.phoneNum
     *
     * @return the value of data.phoneNum
     *
     * @mbg.generated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.phoneNum
     *
     * @param phonenum the value for data.phoneNum
     *
     * @mbg.generated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.remark
     *
     * @return the value of data.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.remark
     *
     * @param remark the value for data.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.status
     *
     * @return the value of data.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.status
     *
     * @param status the value for data.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}