package com.tencent.wxcloudrun.model;

import java.util.ArrayList;
import java.util.List;

public class DataPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    public DataPoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("`num` is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("`num` is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("`num` =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("`num` <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("`num` >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("`num` >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("`num` <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("`num` <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("`num` like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("`num` not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("`num` in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("`num` not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("`num` between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("`num` not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("`code` is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("`code` is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("`code` =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("`code` <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("`code` >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("`code` >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("`code` <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("`code` <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("`code` like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("`code` not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("`code` in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("`code` not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("`code` between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("`code` not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("`address` is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("`address` is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("`address` =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("`address` <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("`address` >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("`address` >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("`address` <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("`address` <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("`address` like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("`address` not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("`address` in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("`address` not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("`address` between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("`address` not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("`pid` is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("`pid` is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("`pid` =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("`pid` <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("`pid` >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("`pid` >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("`pid` <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("`pid` <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("`pid` like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("`pid` not like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("`pid` in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("`pid` not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("`pid` between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("`pid` not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andAttributeIsNull() {
            addCriterion("`attribute` is null");
            return (Criteria) this;
        }

        public Criteria andAttributeIsNotNull() {
            addCriterion("`attribute` is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeEqualTo(String value) {
            addCriterion("`attribute` =", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeNotEqualTo(String value) {
            addCriterion("`attribute` <>", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeGreaterThan(String value) {
            addCriterion("`attribute` >", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeGreaterThanOrEqualTo(String value) {
            addCriterion("`attribute` >=", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeLessThan(String value) {
            addCriterion("`attribute` <", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeLessThanOrEqualTo(String value) {
            addCriterion("`attribute` <=", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeLike(String value) {
            addCriterion("`attribute` like", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeNotLike(String value) {
            addCriterion("`attribute` not like", value, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeIn(List<String> values) {
            addCriterion("`attribute` in", values, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeNotIn(List<String> values) {
            addCriterion("`attribute` not in", values, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeBetween(String value1, String value2) {
            addCriterion("`attribute` between", value1, value2, "attribute");
            return (Criteria) this;
        }

        public Criteria andAttributeNotBetween(String value1, String value2) {
            addCriterion("`attribute` not between", value1, value2, "attribute");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("`type` like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("`type` not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andRoundIsNull() {
            addCriterion("`round` is null");
            return (Criteria) this;
        }

        public Criteria andRoundIsNotNull() {
            addCriterion("`round` is not null");
            return (Criteria) this;
        }

        public Criteria andRoundEqualTo(String value) {
            addCriterion("`round` =", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundNotEqualTo(String value) {
            addCriterion("`round` <>", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundGreaterThan(String value) {
            addCriterion("`round` >", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundGreaterThanOrEqualTo(String value) {
            addCriterion("`round` >=", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundLessThan(String value) {
            addCriterion("`round` <", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundLessThanOrEqualTo(String value) {
            addCriterion("`round` <=", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundLike(String value) {
            addCriterion("`round` like", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundNotLike(String value) {
            addCriterion("`round` not like", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundIn(List<String> values) {
            addCriterion("`round` in", values, "round");
            return (Criteria) this;
        }

        public Criteria andRoundNotIn(List<String> values) {
            addCriterion("`round` not in", values, "round");
            return (Criteria) this;
        }

        public Criteria andRoundBetween(String value1, String value2) {
            addCriterion("`round` between", value1, value2, "round");
            return (Criteria) this;
        }

        public Criteria andRoundNotBetween(String value1, String value2) {
            addCriterion("`round` not between", value1, value2, "round");
            return (Criteria) this;
        }

        public Criteria andQizhiIsNull() {
            addCriterion("`qizhi` is null");
            return (Criteria) this;
        }

        public Criteria andQizhiIsNotNull() {
            addCriterion("`qizhi` is not null");
            return (Criteria) this;
        }

        public Criteria andQizhiEqualTo(String value) {
            addCriterion("`qizhi` =", value, "qizhi");
            return (Criteria) this;
        }

        public Criteria andQizhiNotEqualTo(String value) {
            addCriterion("`qizhi` <>", value, "qizhi");
            return (Criteria) this;
        }

        public Criteria andQizhiGreaterThan(String value) {
            addCriterion("`qizhi` >", value, "qizhi");
            return (Criteria) this;
        }

        public Criteria andQizhiGreaterThanOrEqualTo(String value) {
            addCriterion("`qizhi` >=", value, "qizhi");
            return (Criteria) this;
        }

        public Criteria andQizhiLessThan(String value) {
            addCriterion("`qizhi` <", value, "qizhi");
            return (Criteria) this;
        }

        public Criteria andQizhiLessThanOrEqualTo(String value) {
            addCriterion("`qizhi` <=", value, "qizhi");
            return (Criteria) this;
        }

        public Criteria andQizhiLike(String value) {
            addCriterion("`qizhi` like", value, "qizhi");
            return (Criteria) this;
        }

        public Criteria andQizhiNotLike(String value) {
            addCriterion("`qizhi` not like", value, "qizhi");
            return (Criteria) this;
        }

        public Criteria andQizhiIn(List<String> values) {
            addCriterion("`qizhi` in", values, "qizhi");
            return (Criteria) this;
        }

        public Criteria andQizhiNotIn(List<String> values) {
            addCriterion("`qizhi` not in", values, "qizhi");
            return (Criteria) this;
        }

        public Criteria andQizhiBetween(String value1, String value2) {
            addCriterion("`qizhi` between", value1, value2, "qizhi");
            return (Criteria) this;
        }

        public Criteria andQizhiNotBetween(String value1, String value2) {
            addCriterion("`qizhi` not between", value1, value2, "qizhi");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("`year` is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("`year` is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(String value) {
            addCriterion("`year` =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(String value) {
            addCriterion("`year` <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(String value) {
            addCriterion("`year` >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(String value) {
            addCriterion("`year` >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(String value) {
            addCriterion("`year` <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(String value) {
            addCriterion("`year` <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLike(String value) {
            addCriterion("`year` like", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotLike(String value) {
            addCriterion("`year` not like", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<String> values) {
            addCriterion("`year` in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<String> values) {
            addCriterion("`year` not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(String value1, String value2) {
            addCriterion("`year` between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(String value1, String value2) {
            addCriterion("`year` not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andTurnIsNull() {
            addCriterion("`turn` is null");
            return (Criteria) this;
        }

        public Criteria andTurnIsNotNull() {
            addCriterion("`turn` is not null");
            return (Criteria) this;
        }

        public Criteria andTurnEqualTo(String value) {
            addCriterion("`turn` =", value, "turn");
            return (Criteria) this;
        }

        public Criteria andTurnNotEqualTo(String value) {
            addCriterion("`turn` <>", value, "turn");
            return (Criteria) this;
        }

        public Criteria andTurnGreaterThan(String value) {
            addCriterion("`turn` >", value, "turn");
            return (Criteria) this;
        }

        public Criteria andTurnGreaterThanOrEqualTo(String value) {
            addCriterion("`turn` >=", value, "turn");
            return (Criteria) this;
        }

        public Criteria andTurnLessThan(String value) {
            addCriterion("`turn` <", value, "turn");
            return (Criteria) this;
        }

        public Criteria andTurnLessThanOrEqualTo(String value) {
            addCriterion("`turn` <=", value, "turn");
            return (Criteria) this;
        }

        public Criteria andTurnLike(String value) {
            addCriterion("`turn` like", value, "turn");
            return (Criteria) this;
        }

        public Criteria andTurnNotLike(String value) {
            addCriterion("`turn` not like", value, "turn");
            return (Criteria) this;
        }

        public Criteria andTurnIn(List<String> values) {
            addCriterion("`turn` in", values, "turn");
            return (Criteria) this;
        }

        public Criteria andTurnNotIn(List<String> values) {
            addCriterion("`turn` not in", values, "turn");
            return (Criteria) this;
        }

        public Criteria andTurnBetween(String value1, String value2) {
            addCriterion("`turn` between", value1, value2, "turn");
            return (Criteria) this;
        }

        public Criteria andTurnNotBetween(String value1, String value2) {
            addCriterion("`turn` not between", value1, value2, "turn");
            return (Criteria) this;
        }

        public Criteria andButienumIsNull() {
            addCriterion("`butieNum` is null");
            return (Criteria) this;
        }

        public Criteria andButienumIsNotNull() {
            addCriterion("`butieNum` is not null");
            return (Criteria) this;
        }

        public Criteria andButienumEqualTo(String value) {
            addCriterion("`butieNum` =", value, "butienum");
            return (Criteria) this;
        }

        public Criteria andButienumNotEqualTo(String value) {
            addCriterion("`butieNum` <>", value, "butienum");
            return (Criteria) this;
        }

        public Criteria andButienumGreaterThan(String value) {
            addCriterion("`butieNum` >", value, "butienum");
            return (Criteria) this;
        }

        public Criteria andButienumGreaterThanOrEqualTo(String value) {
            addCriterion("`butieNum` >=", value, "butienum");
            return (Criteria) this;
        }

        public Criteria andButienumLessThan(String value) {
            addCriterion("`butieNum` <", value, "butienum");
            return (Criteria) this;
        }

        public Criteria andButienumLessThanOrEqualTo(String value) {
            addCriterion("`butieNum` <=", value, "butienum");
            return (Criteria) this;
        }

        public Criteria andButienumLike(String value) {
            addCriterion("`butieNum` like", value, "butienum");
            return (Criteria) this;
        }

        public Criteria andButienumNotLike(String value) {
            addCriterion("`butieNum` not like", value, "butienum");
            return (Criteria) this;
        }

        public Criteria andButienumIn(List<String> values) {
            addCriterion("`butieNum` in", values, "butienum");
            return (Criteria) this;
        }

        public Criteria andButienumNotIn(List<String> values) {
            addCriterion("`butieNum` not in", values, "butienum");
            return (Criteria) this;
        }

        public Criteria andButienumBetween(String value1, String value2) {
            addCriterion("`butieNum` between", value1, value2, "butienum");
            return (Criteria) this;
        }

        public Criteria andButienumNotBetween(String value1, String value2) {
            addCriterion("`butieNum` not between", value1, value2, "butienum");
            return (Criteria) this;
        }

        public Criteria andButiestandardIsNull() {
            addCriterion("`butieStandard` is null");
            return (Criteria) this;
        }

        public Criteria andButiestandardIsNotNull() {
            addCriterion("`butieStandard` is not null");
            return (Criteria) this;
        }

        public Criteria andButiestandardEqualTo(String value) {
            addCriterion("`butieStandard` =", value, "butiestandard");
            return (Criteria) this;
        }

        public Criteria andButiestandardNotEqualTo(String value) {
            addCriterion("`butieStandard` <>", value, "butiestandard");
            return (Criteria) this;
        }

        public Criteria andButiestandardGreaterThan(String value) {
            addCriterion("`butieStandard` >", value, "butiestandard");
            return (Criteria) this;
        }

        public Criteria andButiestandardGreaterThanOrEqualTo(String value) {
            addCriterion("`butieStandard` >=", value, "butiestandard");
            return (Criteria) this;
        }

        public Criteria andButiestandardLessThan(String value) {
            addCriterion("`butieStandard` <", value, "butiestandard");
            return (Criteria) this;
        }

        public Criteria andButiestandardLessThanOrEqualTo(String value) {
            addCriterion("`butieStandard` <=", value, "butiestandard");
            return (Criteria) this;
        }

        public Criteria andButiestandardLike(String value) {
            addCriterion("`butieStandard` like", value, "butiestandard");
            return (Criteria) this;
        }

        public Criteria andButiestandardNotLike(String value) {
            addCriterion("`butieStandard` not like", value, "butiestandard");
            return (Criteria) this;
        }

        public Criteria andButiestandardIn(List<String> values) {
            addCriterion("`butieStandard` in", values, "butiestandard");
            return (Criteria) this;
        }

        public Criteria andButiestandardNotIn(List<String> values) {
            addCriterion("`butieStandard` not in", values, "butiestandard");
            return (Criteria) this;
        }

        public Criteria andButiestandardBetween(String value1, String value2) {
            addCriterion("`butieStandard` between", value1, value2, "butiestandard");
            return (Criteria) this;
        }

        public Criteria andButiestandardNotBetween(String value1, String value2) {
            addCriterion("`butieStandard` not between", value1, value2, "butiestandard");
            return (Criteria) this;
        }

        public Criteria andShouldamountIsNull() {
            addCriterion("`shouldAmount` is null");
            return (Criteria) this;
        }

        public Criteria andShouldamountIsNotNull() {
            addCriterion("`shouldAmount` is not null");
            return (Criteria) this;
        }

        public Criteria andShouldamountEqualTo(String value) {
            addCriterion("`shouldAmount` =", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountNotEqualTo(String value) {
            addCriterion("`shouldAmount` <>", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountGreaterThan(String value) {
            addCriterion("`shouldAmount` >", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountGreaterThanOrEqualTo(String value) {
            addCriterion("`shouldAmount` >=", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountLessThan(String value) {
            addCriterion("`shouldAmount` <", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountLessThanOrEqualTo(String value) {
            addCriterion("`shouldAmount` <=", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountLike(String value) {
            addCriterion("`shouldAmount` like", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountNotLike(String value) {
            addCriterion("`shouldAmount` not like", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountIn(List<String> values) {
            addCriterion("`shouldAmount` in", values, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountNotIn(List<String> values) {
            addCriterion("`shouldAmount` not in", values, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountBetween(String value1, String value2) {
            addCriterion("`shouldAmount` between", value1, value2, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountNotBetween(String value1, String value2) {
            addCriterion("`shouldAmount` not between", value1, value2, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andActualamountIsNull() {
            addCriterion("`actualAmount` is null");
            return (Criteria) this;
        }

        public Criteria andActualamountIsNotNull() {
            addCriterion("`actualAmount` is not null");
            return (Criteria) this;
        }

        public Criteria andActualamountEqualTo(String value) {
            addCriterion("`actualAmount` =", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountNotEqualTo(String value) {
            addCriterion("`actualAmount` <>", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountGreaterThan(String value) {
            addCriterion("`actualAmount` >", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountGreaterThanOrEqualTo(String value) {
            addCriterion("`actualAmount` >=", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountLessThan(String value) {
            addCriterion("`actualAmount` <", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountLessThanOrEqualTo(String value) {
            addCriterion("`actualAmount` <=", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountLike(String value) {
            addCriterion("`actualAmount` like", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountNotLike(String value) {
            addCriterion("`actualAmount` not like", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountIn(List<String> values) {
            addCriterion("`actualAmount` in", values, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountNotIn(List<String> values) {
            addCriterion("`actualAmount` not in", values, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountBetween(String value1, String value2) {
            addCriterion("`actualAmount` between", value1, value2, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountNotBetween(String value1, String value2) {
            addCriterion("`actualAmount` not between", value1, value2, "actualamount");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("`account` is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("`account` is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("`account` =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("`account` <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("`account` >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("`account` >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("`account` <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("`account` <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("`account` like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("`account` not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("`account` in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("`account` not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("`account` between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("`account` not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andIssuedateIsNull() {
            addCriterion("`issueDate` is null");
            return (Criteria) this;
        }

        public Criteria andIssuedateIsNotNull() {
            addCriterion("`issueDate` is not null");
            return (Criteria) this;
        }

        public Criteria andIssuedateEqualTo(String value) {
            addCriterion("`issueDate` =", value, "issuedate");
            return (Criteria) this;
        }

        public Criteria andIssuedateNotEqualTo(String value) {
            addCriterion("`issueDate` <>", value, "issuedate");
            return (Criteria) this;
        }

        public Criteria andIssuedateGreaterThan(String value) {
            addCriterion("`issueDate` >", value, "issuedate");
            return (Criteria) this;
        }

        public Criteria andIssuedateGreaterThanOrEqualTo(String value) {
            addCriterion("`issueDate` >=", value, "issuedate");
            return (Criteria) this;
        }

        public Criteria andIssuedateLessThan(String value) {
            addCriterion("`issueDate` <", value, "issuedate");
            return (Criteria) this;
        }

        public Criteria andIssuedateLessThanOrEqualTo(String value) {
            addCriterion("`issueDate` <=", value, "issuedate");
            return (Criteria) this;
        }

        public Criteria andIssuedateLike(String value) {
            addCriterion("`issueDate` like", value, "issuedate");
            return (Criteria) this;
        }

        public Criteria andIssuedateNotLike(String value) {
            addCriterion("`issueDate` not like", value, "issuedate");
            return (Criteria) this;
        }

        public Criteria andIssuedateIn(List<String> values) {
            addCriterion("`issueDate` in", values, "issuedate");
            return (Criteria) this;
        }

        public Criteria andIssuedateNotIn(List<String> values) {
            addCriterion("`issueDate` not in", values, "issuedate");
            return (Criteria) this;
        }

        public Criteria andIssuedateBetween(String value1, String value2) {
            addCriterion("`issueDate` between", value1, value2, "issuedate");
            return (Criteria) this;
        }

        public Criteria andIssuedateNotBetween(String value1, String value2) {
            addCriterion("`issueDate` not between", value1, value2, "issuedate");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateIsNull() {
            addCriterion("`registrationDate` is null");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateIsNotNull() {
            addCriterion("`registrationDate` is not null");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateEqualTo(String value) {
            addCriterion("`registrationDate` =", value, "registrationdate");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateNotEqualTo(String value) {
            addCriterion("`registrationDate` <>", value, "registrationdate");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateGreaterThan(String value) {
            addCriterion("`registrationDate` >", value, "registrationdate");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateGreaterThanOrEqualTo(String value) {
            addCriterion("`registrationDate` >=", value, "registrationdate");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateLessThan(String value) {
            addCriterion("`registrationDate` <", value, "registrationdate");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateLessThanOrEqualTo(String value) {
            addCriterion("`registrationDate` <=", value, "registrationdate");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateLike(String value) {
            addCriterion("`registrationDate` like", value, "registrationdate");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateNotLike(String value) {
            addCriterion("`registrationDate` not like", value, "registrationdate");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateIn(List<String> values) {
            addCriterion("`registrationDate` in", values, "registrationdate");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateNotIn(List<String> values) {
            addCriterion("`registrationDate` not in", values, "registrationdate");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateBetween(String value1, String value2) {
            addCriterion("`registrationDate` between", value1, value2, "registrationdate");
            return (Criteria) this;
        }

        public Criteria andRegistrationdateNotBetween(String value1, String value2) {
            addCriterion("`registrationDate` not between", value1, value2, "registrationdate");
            return (Criteria) this;
        }

        public Criteria andPhonenumIsNull() {
            addCriterion("`phoneNum` is null");
            return (Criteria) this;
        }

        public Criteria andPhonenumIsNotNull() {
            addCriterion("`phoneNum` is not null");
            return (Criteria) this;
        }

        public Criteria andPhonenumEqualTo(String value) {
            addCriterion("`phoneNum` =", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumNotEqualTo(String value) {
            addCriterion("`phoneNum` <>", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumGreaterThan(String value) {
            addCriterion("`phoneNum` >", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumGreaterThanOrEqualTo(String value) {
            addCriterion("`phoneNum` >=", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumLessThan(String value) {
            addCriterion("`phoneNum` <", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumLessThanOrEqualTo(String value) {
            addCriterion("`phoneNum` <=", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumLike(String value) {
            addCriterion("`phoneNum` like", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumNotLike(String value) {
            addCriterion("`phoneNum` not like", value, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumIn(List<String> values) {
            addCriterion("`phoneNum` in", values, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumNotIn(List<String> values) {
            addCriterion("`phoneNum` not in", values, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumBetween(String value1, String value2) {
            addCriterion("`phoneNum` between", value1, value2, "phonenum");
            return (Criteria) this;
        }

        public Criteria andPhonenumNotBetween(String value1, String value2) {
            addCriterion("`phoneNum` not between", value1, value2, "phonenum");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("`remark` is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("`remark` is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("`remark` =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("`remark` <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("`remark` >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("`remark` >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("`remark` <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("`remark` <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("`remark` like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("`remark` not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("`remark` in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("`remark` not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("`remark` between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("`remark` not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}